### ISSUE TITLE
Network: Error

### ISSUE THREAD

**Issue by DimitarYakov** [nfcgate/server#3]
Hello, may i ask....is ti possible to connect with server from phone with mobile data on and different ip from the machine where server is running ? I was trying and it show me on the app "Network:error" . Thanks in advance.

**Comment by roussosalex** [comment]
Hello, while it is possible to connect to the server from a mobile data network, please remember that the data is transmitted _without any encryption_ and we do not recommend using it for sensitive data like credit card and passport information. 

In order to connect to the server from the internet you need to make sure no firewall on your server machine is blocking incoming connections and the servers network is properly configured to accept external connections (e.g. [port forwarding](https://www.noip.com/support/knowledgebase/general-port-forwarding-guide/) in a router).
